stages:
  - build

variables:
  DOTNET_VERSION: '6.0.x'

before_script:
  - apt-get update -qy
  - apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  - export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1

build:
  stage: build
  script:
    - apt-get install -y dotnet-sdk-${DOTNET_VERSION}
    - dotnet restore
    - dotnet test --logger trx --results-directory "TestResults-${DOTNET_VERSION}"
  artifacts:
    paths:
      - TestResults-${DOTNET_VERSION}